


# Application and container name 
dump1090AppName: dump1090

# Internal service port for stats web page
dump1090ExposedSvc: 30005
dump1090ExposedSvcHttp: 80

service:
  beast: "dump1090-beast"
  http: "dump1090"
# Ingress settings for FlightRadar24 stats web page
ingress:
  enabled: false
  hostname: dump1090.ingress.local

# Namespace
namespace: "default"

# Host and internal pod mounted USB device for RTL-SDR messages gathering
dump1090usbPath: "/dev/bus/usb"

dump1090exporter:
  name: "dump1090-exporter"
  enabled: true
  image: "fnzv/dump1090-exporter"
  port: 9105
  dump1090Url: "http://dump1090/data"
  exporterHost: "0.0.0.0"
  aircraftInterval: "10"
  statsInterval: "60"
  receiverInterval: "10"
  receiverLatitude: "123.123"
  receiverLongitude: "123.123"
  logLevel: "info"

