apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.dump1090AppName | default "dump1090" }}
  template:
    metadata:
      labels:
        app: {{ .Values.dump1090AppName | default "dump1090" }}
    spec:
      containers:
      - name: {{ .Values.dump1090AppName | default "dump1090" }}
        image: fnzv/dump1090:latest
        ports:
         - containerPort: 8080
        securityContext:
          privileged: true  # Allow the container to access devices
        volumeMounts:
        - name: usb-volume
          mountPath: {{ .Values.dump1090usbPath | default "/dev/bus/usb" }}
      volumes:
      - name: usb-volume
        hostPath:
          path: {{ .Values.dump1090usbPath | default "/dev/bus/usb" }}

---
{{- if .Values.dump1090exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.dump1090exporter.name | default "dump1090exporter" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.dump1090exporter.name | default "dump1090exporter" }}
  template:
    metadata:
      labels:
        app: {{ .Values.dump1090exporter.name | default "dump1090exporter" }}
    spec:
      containers:
      - name: {{ .Values.dump1090exporter.name | default "dump1090exporter" }}
        image: {{ .Values.dump1090exporter.image }}
        ports:
        - containerPort: {{ .Values.dump1090exporter.port }}
        env:
        - name: DUMP1090_URL
          value: {{ .Values.dump1090exporter.dump1090Url | quote }}
        - name: EXPORTER_HOST
          value: {{ .Values.dump1090exporter.exporterHost | quote }}
        - name: AIRCRAFT_INTERVAL
          value: {{ .Values.dump1090exporter.aircraftInterval | quote }}
        - name: STATS_INTERVAL
          value: {{ .Values.dump1090exporter.statsInterval | quote }}
        - name: RECEIVER_INTERVAL
          value: {{ .Values.dump1090exporter.receiverInterval | quote }}
        - name: RECEIVER_LATITUDE
          value: {{ .Values.dump1090exporter.receiverLatitude | quote }}
        - name: RECEIVER_LONGITUDE
          value: {{ .Values.dump1090exporter.receiverLongitude | quote }}
        - name: LOG_LEVEL
          value: {{ .Values.dump1090exporter.logLevel | quote }}
{{- end }}

