apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.beast | default "dump1090-beast" }}
spec:
  selector:
    app: {{ .Values.dump1090AppName | default "dump1090" }}
  ports:
    - protocol: TCP
      port: {{ .Values.dump1090ExposedSvc | default "30005" }}
      targetPort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dump1090AppName | default "dump1090" }}
spec:
  selector:
    app: {{ .Values.dump1090AppName | default "dump1090" }}
  ports:
    - protocol: TCP
      port: {{ .Values.dump1090ExposedSvcHttp | default "80" }}
      targetPort: 8080
{{- if .Values.dump1090-exporter.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ index .Values "dump1090-exporter" "name" }}
spec:
  selector:
    app: {{ index .Values "dump1090-exporter" "name" }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9105
{{- end }}

